exotic_names = [
    # ChineseNames
    'Li', 'Zhang', 'Chen', 'Wang', 'Zhao', 'Liu', 'Xiao', 'Yang', 'Huang',
    'Xu', 'Sun', 'Ma', 'Zhu', 'Gao', 'Lin', 'He', 'Guo', 'Deng', 'Hu',
    'Kong', 'Fang', 'Bai', 'Jin', 'Shi', 'Qian', 'Tian', 'Tang', 'Wu',
    'Yuan', 'Xie', 'Song', 'Zou', 'Yan', 'Feng', 'Du', 'Lu', 'Cao', 'Pan',
    'Yu', 'Yao', 'Zeng', 'Niu', 'Xiong', 'Fang', 'Ren', 'Jiang', 'Fu', 'Zong',
    'Luo', 'Zuo', 'Chang', 'Wen', 'Shen', 'Qin', 'Ding', 'Zhai', 'Zeng', 'Yi',
    'Liang', 'Zhou', 'Qiu', 'Yu', 'Han', 'Xiang', 'Cheng', 'Jia', 'Jiang', 'Hou',
    'Chu', 'Zuo', 'Wan', 'Shi', 'Ying', 'Yin', 'Ning', 'Tang', 'Long', 'Hao',
    'Nan', 'Zhong', 'Qing', 'Xu', 'Hong', 'Meng', 'Chen', 'Bao', 'Ying', 'Xia',
    'Gui', '', 'Kang', 'Hu', 'Hui', 'Ling', 'Chao', 'Zhen', 'Hui', 'Xi',
    'Shuai', 'Xu', 'Wang', 'Bo', 'Shao', 'Gan', 'Ming', 'Wang', 'Zhu', 'Feng',
    'Jie', 'Qin', 'Quan', 'Sui', 'Xuan', 'Zi', 'Xing', 'Chuang', '', 'Jin',
    'Chun', 'Peng', 'Yu', 'Hong', 'Duan', 'Dai', 'Lei', 'Huan', 'Yuan', 'Kun',
    'Fu', 'Tao', 'Xun', 'Lan', 'Xiang', 'Chen', 'Dong', 'Shun', 'Hai', 'Yi',
    'Sheng', 'Shi', 'Wu', 'Yun', 'Tong', 'Hua', 'Yu', '', 'Jin', 'Si',
    'Bo', 'Zhong', 'Ling', 'Yu', 'Feng', 'Ding', 'Kai', 'Jiang', 'Lin', 'Xiao',
    'Xia', 'An', 'Xing', 'Qian', 'Cai', 'Yue', 'Tian', 'Zhou', 'Chang', 'Niu',
    'Yan', 'Qu', 'Kang', 'Gu', 'Tang', 'Hou', 'Yao', 'Hao', 'Deng', 'Qin',
    'Shi', 'Wen', 'Mao', 'Nan', 'Shen', 'Yi', 'Sheng', 'Xin', '', 'Bo',
    'Kun', 'Yong', '', 'Zi', 'Shi', 'Chun', 'Yi', 'Xin', 'Peng', 'Yun',
    'Rong', 'Yang', 'Tong', 'Dong', 'Jin', 'Ying', 'Qin', 'Gong', 'Qiang', 'Tao',
    'Xiang', 'Zhao', '', 'Liu', 'Guang', 'Hua', 'Li', 'Xin', 'Xing', 'Xiang',
    'Hong', 'Wen', 'Yi', '', 'Ming', 'Qian', 'Zhi', '', 'Jin', 'Zhen',
    'Xiang', 'Shi', 'Ming', 'Wu', 'Yuan', 'Hao', 'Yu', 'Yong', 'Yi', 'Hong',
    'Zhu', 'Jin', '', 'Ming', 'Jun', 'Zheng', 'Li', 'Zhou', 'Zhi', 'Yi',
    'Guo', '', 'Zhong', 'Jia', 'Liang', '', 'Shi', 'Guang', 'Jin', 'Yuan',
    'Zhou', 'Yan', 'Xin', 'Xu', 'Liang', '', 'Li', 'Shi', 'Yong', 'Hong',
    'Chen', '', 'Ming', 'Yi', 'Shu', 'Zhong', 'Xing', 'Zheng', 'Hao', 'Zhang',
    'Xin', 'Xiang', '', 'Xiao', 'Qian', 'Xu', 'Chang', 'Li', 'Yong', 'Xin',
    'Zhang', 'Xiang', 'Zhou', 'Liang', 'Chen', 'Ming', 'Jin', '', 'Yi',

    # JapaneseNames
    'Haruto', 'Yuto', 'Sota', 'Riku', 'Kaito', 'Yuya', 'Yuma', 'Yuki', 'Haruki', 'Sora',
    'Ren', 'Soma', 'Ryo', 'Aoi', 'Takumi', 'Rui', 'Hayato', 'Koki', 'Takeru', 'Rikuto',
    'Shota', 'Taiga', 'Sho', 'Daiki', 'Kota', 'Sosuke', 'Shunya', 'Kazu', 'Yusei', 'Kazuki',
    'Koki', 'Hikaru', 'Minato', 'Kosuke', 'Ryota', 'Sota', 'Toma', 'Hiroto', 'Kenta', 'Shun',
    'Yuto', 'Yuki', 'Haruto', 'Yuto', 'Sota', 'Riku', 'Kaito', 'Yuya', 'Yuma', 'Yuki',
    'Haruki', 'Sora', 'Ren', 'Soma', 'Ryo', 'Aoi', 'Takumi', 'Rui', 'Hayato', 'Koki',
    'Takeru', 'Rikuto', 'Shota', 'Taiga', 'Sho', 'Daiki', 'Kota', 'Sosuke', 'Shunya', 'Kazu',
    'Yusei', 'Kazuki', 'Koki', 'Hikaru', 'Minato', 'Kosuke', 'Ryota', 'Sota', 'Toma', 'Hiroto',
    'Kenta', 'Shun', 'Yuto', 'Yuki', 'Haruto', 'Yuto', 'Sota', 'Riku', 'Kaito', 'Yuya',
    'Yuma', 'Yuki', 'Haruki', 'Sora', 'Ren', 'Soma', 'Ryo', 'Aoi', 'Takumi', 'Rui',
    'Hayato', 'Koki', 'Takeru', 'Rikuto', 'Shota', 'Taiga', 'Sho', 'Daiki', 'Kota', 'Sosuke',
    'Shunya', 'Kazu', 'Yusei', 'Kazuki', 'Koki', 'Hikaru', 'Minato', 'Kosuke', 'Ryota', 'Sota',
    'Toma', 'Hiroto', 'Kenta', 'Shun', 'Yuto', 'Yuki', 'Haruto', 'Yuto', 'Sota', 'Riku',
    'Kaito', 'Yuya', 'Yuma', 'Yuki', 'Haruki', 'Sora', 'Ren', 'Soma', 'Ryo', 'Aoi',
    'Takumi', 'Rui', 'Hayato', 'Koki', 'Takeru', 'Rikuto', 'Shota', 'Taiga', 'Sho', 'Daiki',
    'Kota', 'Sosuke', 'Shunya', 'Kazu', 'Yusei', 'Kazuki', 'Koki', 'Hikaru', 'Minato', 'Kosuke',
    'Ryota', 'Sota', 'Toma', 'Hiroto', 'Kenta', 'Shun', 'Yuto', 'Yuki', 'Haruto', 'Yuto',
    'Sota', 'Riku', 'Kaito', 'Yuya', 'Yuma', 'Yuki', 'Haruki', 'Sora', 'Ren', 'Soma',
    'Ryo', 'Aoi', 'Takumi', 'Rui', 'Hayato', 'Koki', 'Takeru', 'Rikuto', 'Shota', 'Taiga',
    'Sho', 'Daiki', 'Kota', 'Sosuke', 'Shunya', 'Kazu', 'Yusei', 'Kazuki', 'Koki', 'Hikaru',
    'Minato', 'Kosuke', 'Ryota', 'Sota', 'Toma', 'Hiroto', 'Kenta', 'Shun', 'Yuto', 'Yuki',
    'Haruto', 'Yuto', 'Sota', 'Riku', 'Kaito', 'Yuya', 'Yuma', 'Yuki', 'Haruki', 'Sora',
    'Ren', 'Soma', 'Ryo', 'Aoi', 'Takumi', 'Rui', 'Hayato', 'Koki', 'Takeru', 'Rikuto',
    'Shota', 'Taiga', 'Sho', 'Daiki', 'Kota', 'Sosuke', 'Shunya', 'Kazu', 'Yusei', 'Kazuki',
    'Koki', 'Hikaru', 'Minato', 'Kosuke', 'Ryota', 'Sota', 'Toma', 'Hiroto', 'Kenta', 'Shun',
    'Yuto', 'Yuki', 'Haruto', 'Yuto', 'Sota', 'Riku', 'Kaito', 'Yuya', 'Yuma', 'Yuki',
    'Haruki', 'Sora', 'Ren', 'Soma', 'Ryo', 'Aoi', 'Takumi', 'Rui', 'Hayato', 'Koki',
    'Takeru', 'Rikuto', 'Shota', 'Taiga', 'Sho', 'Daiki', 'Kota', 'Sosuke', 'Shunya', 'Kazu',
    'Yusei', 'Kazuki', 'Koki', 'Hikaru', 'Minato', 'Kosuke', 'Ryota', 'Sota', 'Toma', 'Hiroto',
    'Kenta', 'Shun', 'Yuto', 'Yuki', 'Haruto', 'Yuto', 'Sota', 'Riku', 'Kaito', 'Yuya',
    'Yuma', 'Yuki', 'Haruki', 'Sora', 'Ren', 'Soma', 'Ryo', 'Aoi', 'Takumi', 'Rui',
    'Hayato', 'Koki', 'Takeru', 'Rikuto', 'Shota', 'Taiga', 'Sho', 'Daiki', 'Kota', 'Sosuke',
    'Shunya', 'Kazu', 'Yusei', 'Kazuki', 'Koki', 'Hikaru', 'Minato', 'Kosuke', 'Ryota', 'Sota',
    'Toma', 'Hiroto', 'Kenta', 'Shun', 'Yuto', 'Yuki', 'Haruto', 'Yuto', 'Sota', 'Riku',
    'Kaito', 'Yuya', 'Yuma', 'Yuki', 'Haruki', 'Sora', 'Ren', 'Soma', 'Ryo', 'Aoi',
    'Takumi', 'Rui', 'Hayato', 'Koki', 'Takeru', 'Rikuto', 'Shota', 'Taiga', 'Sho', 'Daiki',
    'Kota', 'Sosuke', 'Shunya', 'Kazu', 'Yusei', 'Kazuki', 'Koki', 'Hikaru', 'Minato', 'Kosuke',
    'Ryota', 'Sota', 'Toma', 'Hiroto', 'Kenta', 'Shun', 'Yuto', 'Yuki', 'Haruto', 'Yuto',
    'Sota', 'Riku', 'Kaito', 'Yuya', 'Yuma', 'Yuki', 'Haruki', 'Sora', 'Ren', 'Soma',
    'Ryo', 'Aoi', 'Takumi', 'Rui', 'Hayato', 'Koki', 'Takeru', 'Rikuto', 'Shota', 'Taiga',
    'Sho', 'Daiki', 'Kota', 'Sosuke', 'Shunya', 'Kazu', 'Yusei', 'Kazuki', 'Koki', 'Hikaru',
    'Minato', 'Kosuke', 'Ryota', 'Sota', 'Toma', 'Hiroto', 'Kenta', 'Shun', 'Yuto', 'Yuki',
    'Haruto', 'Yuto', 'Sota', 'Riku', 'Kaito', 'Yuya', 'Yuma', 'Yuki', 'Haruki', 'Sora',
    'Ren', 'Soma', 'Ryo', 'Aoi', 'Takumi', 'Rui', 'Hayato', 'Koki', 'Takeru', 'Rikuto',
    'Shota', 'Taiga', 'Sho', 'Daiki', 'Kota', 'Sosuke', 'Shunya', 'Kazu', 'Yusei', 'Kazuki',
    'Koki', 'Hikaru', 'Minato', 'Kosuke', 'Ryota', 'Sota', 'Toma', 'Hiroto', 'Kenta', 'Shun',

    # ScandinavianNames
    'Lars', 'Erik', 'Hans', 'Ole', 'Per', 'Jan', 'Kjell', 'Anders', 'Sven', 'Nils',
    'Mats', 'Bjorn', 'Stig', 'Gunnar', 'Leif', 'Jorgen', 'Arne', 'Lennart', 'Sten', 'Johan',
    'Karl', 'Ulf', 'Tor', 'Oskar', 'Joakim', 'Petter', 'Tom', 'Daniel', 'Magnus', 'Fredrik',
    'David', 'Jonas', 'Henrik', 'Gustav', 'Christian', 'Mikael', 'Stefan', 'Bo', 'Martin', 'Lennart',
    'Emil', 'Pontus', 'Andreas', 'Hakan', 'Linus', 'Marcus', 'Mikael', 'Klas', 'Hampus', 'Jakob',
    'Mathias', 'Joel', 'Kurt', 'Ludvig', 'Olof', 'Simon', 'Thomas', 'Sebastian', 'Axel', 'Viktor',
    'Elias', 'Niklas', 'Lukas', 'Filip', 'William', 'Christopher', 'Robert', 'Gabriel', 'Adam', 'Philip',
    'Noah', 'Kevin', 'Charlie', 'Theo', 'Alexander', 'Leo', 'Elliot', 'Samuel', 'Vincent', 'Oliver',
    'Isaac', 'Henry', 'Lucas', 'Benjamin', 'David', 'Liam', 'Jack', 'Leo', 'Henry', 'Mason',
    'William', 'Thomas', 'Joseph', 'James', 'Daniel', 'Alexander', 'Samuel', 'Matthew', 'Oliver', 'Lucas',
    'Jackson', 'Benjamin', 'David', 'John', 'Elijah', 'Gabriel', 'Luke', 'Anthony', 'Dylan', 'Nicholas',
    'Aiden', 'Andrew', 'Joseph', 'Joshua', 'Christopher', 'Mason', 'Daniel', 'David', 'Ryan', 'Ethan',
    'William', 'Emma', 'Olivia', 'Ava', 'Sophia', 'Isabella', 'Mia', 'Charlotte', 'Abigail', 'Emily',
    'Harper', 'Madison', 'Elizabeth', 'Amelia', 'Evelyn', 'Avery', 'Sofia', 'Ella', 'Chloe', 'Grace',
    'Victoria', 'Aubrey', 'Zoe', 'Natalie', 'Addison', 'Lillian', 'Brooklyn', 'Lily', 'Hannah', 'Nora',
    'Scarlett', 'Lucy', 'Eleanor', 'Leah', 'Alice', 'Claire', 'Samantha', 'Ellie', 'Stella', 'Anna',
    'Lillian', 'Grace', 'Harper', 'Nora', 'Scarlett', 'Zoey', 'Violet', 'Claire', 'Aurora', 'Audrey',
    'Lucy', 'Sarah', 'Caroline', 'Evelyn', 'Amelia', 'Genesis', 'Aaliyah', 'Kennedy', 'Savannah', 'Allison',
    'Samantha', 'Gabriella', 'Sadie', 'Josephine', 'Penelope', 'Naomi', 'Alice', 'Grace', 'Chloe', 'Valentina',
    'Nina', 'Ruby', 'Brielle', 'Jade', 'Anastasia', 'Katherine', 'Vivian', 'Alexa', 'Hadley', 'Bella',
    'Brianna', 'Madelyn', 'Riley', 'Natalie', 'Leilani', 'Angelina', 'Willow', 'Adalyn', 'Eliana', 'Emery',
    'Ana', 'Julia', 'Katherine', 'Arya', 'Juliana', 'Valerie', 'Melanie', 'Delilah', 'Alexandra', 'Marley',
    'Lila', 'Kylie', 'Emilia', 'Sara', 'Adeline', 'Rebecca', 'Julianna', 'Brooke', 'Michelle', 'Haley',

    # ArabicNames
    'Mohammed', 'Adam', 'Youssef', 'Rayan', 'Abdullah', 'Ali', 'Omar', 'Ahmed', 'Hamza', 'Khalid',
    'Zakaria', 'Sami', 'Yassin', 'Ibrahim', 'Amir', 'Nassim', 'Walid', 'Nabil', 'Kamal', 'Mehdi',
    'Hassan', 'Karim', 'Said', 'Bilal', 'Amine', 'Hicham', 'Fares', 'Hichem', 'Fahd', 'Younes',
    'Othmane', 'Yahya', 'Aymen', 'Imran', 'Marwan', 'Anas', 'Wassim', 'Reda', 'Aziz', 'Yassine',
    'Ayoub', 'Mohammed', 'Adam', 'Youssef', 'Rayan', 'Abdullah', 'Ali', 'Omar', 'Ahmed', 'Hamza',
    'Khalid', 'Zakaria', 'Sami', 'Yassin', 'Ibrahim', 'Amir', 'Nassim', 'Walid', 'Nabil', 'Kamal',
    'Mehdi', 'Hassan', 'Karim', 'Said', 'Bilal', 'Amine', 'Hicham', 'Fares', 'Hichem', 'Fahd',
    'Younes', 'Othmane', 'Yahya', 'Aymen', 'Imran', 'Marwan', 'Anas', 'Wassim', 'Reda', 'Aziz',
    'Yassine', 'Ayoub', 'Mohammed', 'Adam', 'Youssef', 'Rayan', 'Abdullah', 'Ali', 'Omar', 'Ahmed',
    'Hamza', 'Khalid', 'Zakaria', 'Sami', 'Yassin', 'Ibrahim', 'Amir', 'Nassim', 'Walid', 'Nabil',
    'Kamal', 'Mehdi', 'Hassan', 'Karim', 'Said', 'Bilal', 'Amine', 'Hicham', 'Fares', 'Hichem',
    'Fahd', 'Younes', 'Othmane', 'Yahya', 'Aymen', 'Imran', 'Marwan', 'Anas', 'Wassim', 'Reda',
    'Aziz', 'Yassine', 'Ayoub', 'Mohammed', 'Adam', 'Youssef', 'Rayan', 'Abdullah', 'Ali', 'Omar',
    'Ahmed', 'Hamza', 'Khalid', 'Zakaria', 'Sami', 'Yassin', 'Ibrahim', 'Amir', 'Nassim', 'Walid',
    'Nabil', 'Kamal', 'Mehdi', 'Hassan', 'Karim', 'Said', 'Bilal', 'Amine', 'Hicham', 'Fares',
    'Hichem', 'Fahd', 'Younes', 'Othmane', 'Yahya', 'Aymen', 'Imran', 'Marwan', 'Anas', 'Wassim',
    'Reda', 'Aziz', 'Yassine', 'Ayoub', 'Mohammed', 'Adam', 'Youssef', 'Rayan', 'Abdullah', 'Ali',
    'Omar', 'Ahmed', 'Hamza', 'Khalid', 'Zakaria', 'Sami', 'Yassin', 'Ibrahim', 'Amir', 'Nassim',
    'Walid', 'Nabil', 'Kamal', 'Mehdi', 'Hassan', 'Karim', 'Said', 'Bilal', 'Amine', 'Hicham',
    'Fares', 'Hichem', 'Fahd', 'Younes', 'Othmane', 'Yahya', 'Aymen', 'Imran', 'Marwan', 'Anas',
    'Wassim', 'Reda', 'Aziz', 'Yassine', 'Ayoub', 'Mohammed', 'Adam', 'Youssef', 'Rayan', 'Abdullah',
    'Ali', 'Omar', 'Ahmed', 'Hamza', 'Khalid', 'Zakaria', 'Sami', 'Yassin', 'Ibrahim', 'Amir',
    'Nassim', 'Walid', 'Nabil', 'Kamal', 'Mehdi', 'Hassan', 'Karim', 'Said', 'Bilal', 'Amine',
    'Hicham', 'Fares', 'Hichem', 'Fahd', 'Younes', 'Othmane', 'Yahya', 'Aymen', 'Imran', 'Marwan',
    'Anas', 'Wassim', 'Reda', 'Aziz', 'Yassine', 'Ayoub'
]
